### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable while training using lane encoding CNN

### ISSUE THREAD

**Issue by gnsJhenJie** [wasn-lab/Multimodal_Transformer#22]
This error occurred while training using lane encoding CNN.  
```sh
python3 train.py --eval_every 1 --vis_every 1 --conf ../experiments/nuScene/config/config.json --data_name nuScenes --preprocess_workers 8 --batch_size 128 --log_dir ../experiments/nuScene/models --train_epochs 20 --node_freq_mult_train --log_tag Lane_transformer --augment --autoregressive --lane_cnn_encoding --device "cuda:1"
```
## Error message
```
-----------------------
| TRAINING PARAMETERS |
-----------------------
| batch_size: 128
| device: cuda:1
| eval_device: cuda:1
| Learning rate 0.0004
| Autoregressive mode  True
| CNN encoding lane mode  True
| Data augment mode  True
| MHL: 4
| PH: 8
-----------------------
Loaded training data from ../experiments/processed_data/nuScenes_train_lane_full.pkl
Loaded evaluation data from ../experiments/processed_data/nuScenes_val_lane_full.pkl
Created Training Model.
Created Evaluation Model.
  0%|                                                  | 0/4758 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 443, in <module>
    main()
  File "train.py", line 242, in main
    for batch in pbar:
  File "/opt/conda/envs/Fusion_trans/lib/python3.6/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/opt/conda/envs/Fusion_trans/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/conda/envs/Fusion_trans/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/Fusion_trans/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/conda/envs/Fusion_trans/lib/python3.6/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/Fusion_trans/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/Fusion_trans/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/Fusion_trans/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jovyan/local/Multimodal_Transformer/Transformer/model/dataset/dataset.py", line 103, in __getitem__
    self.hyperparams)
  File "/home/jovyan/local/Multimodal_Transformer/Transformer/model/dataset/preprocessing.py", line 193, in get_node_timestep_data
    lanes_t_points = np.array(total_lanes_points[index]) / 80
TypeError: 'NoneType' object is not subscriptable
```

**Comment by minano430** [comment]
so the previous issue fixed?

**Comment by minano430** [comment]
Find out the problem when doing data augmentation the lane data is not copy to the new data.

The fix will be test and will push on github after passing the test.
